name: build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Java setup
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 8
          cache: "gradle"
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build
        run: chmod +x ./gradlew && ./gradlew setupCiWorkspace && ./gradlew build
      - name: Rename build artifacts
        run: mv build/libs/CrossSine-*.jar build/libs/CrossSine-Build.jar
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: CrossSine
          path: build/libs/CrossSine-Build.jar
